name: Deployment

on:
  push:
    branches:
    - master

jobs:
  api_admin:
    runs-on: ubuntu-latest

    needs: [lint, e2e]

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - uses: 47ng/actions-clever-cloud@v1
      with:
        appID: ${{ secrets.CLEVER_APP_ID }}
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
