name: Deployment

on:
  push:
    branches:
      - master
      - github-actions-clever-cloud

jobs:
  deploy_admin:
    runs-on: ubuntu-latest

    steps:
    - uses: 47ng/actions-clever-cloud@v1
      with:
        appID: ${{ secrets.CLEVER_ADMIN_APP_ID }}
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

  deploy_api:
    runs-on: ubuntu-latest

    steps:
    - uses: 47ng/actions-clever-cloud@v1
      with:
        appID: ${{ secrets.CLEVER_API_APP_ID }}
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

