name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Dependencies
      run: yarn install

    - name: Lint & Format
      run: |
        yarn lint
        yarn format:ci
